/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "JS Viewer",
  "description": "Allows you to see your workspace in javascript. You cannot yet edit your workspace in javascript I am still figuring that out. (Will be replaced when penguinmods javascript workspaces release)",
  "credits": [
    {
      "name": "Ark360 (Creator)",
      "link": "https://arkide.site/profile?user=ark"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
  ],
  "tags": [
    "new",
    "beta"
  ],
  "enabledByDefault": false
};
export default manifest;
