/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _asset from "!url-loader!./icons/close.svg";
import _asset2 from "!url-loader!./icons/code.svg";
import _asset3 from "!url-loader!./icons/refresh.svg";

export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "icons/close.svg": _asset,
  "icons/code.svg": _asset2,
  "icons/refresh.svg": _asset3,
};